### ISSUE TITLE
"Child process exited abnormally" when trying to install a new server

### ISSUE THREAD

**Issue by realsliff** [lenosisnickerboa/csgosl#108] opened 2017-12-09 16:24 UTC
Hello!

First I had some issues with an older server and csgosl not starting (with an fatal error), so i decided to try it in a new clean folder. Downloaded fresh csgosl and started it from an new folder with no server inside. It started well but after hitting 'install server', I always get an Applicationerror.

**error message**
```
Applicationerror
Error: child process exited abnormally
```
**details**
```child process exited abnormally
child process exited abnormally
    while executing
"exec "$serverControlScript-status.bat""
    (procedure "DetectServerRunning" line 6)
    invoked from within
"DetectServerRunning"
    (procedure "UpdateServer" line 9)
    invoked from within
"UpdateServer"
    invoked from within
".title.update invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 24)
    invoked from within
"tk::ButtonUp .title.update"
    (command bound to event)
```
I tried different csgosl versions, always the same result.

**Comment by lenosisnickerboa** [comment] 2017-12-11 08:45
Will try to reproduce by installing a new server tonight. It's been a while since I did this so maybe something broke meanwhile.

**Comment by realsliff** [comment] 2017-12-13 20:15
Thanks for your reply!
My csgosl files are in C:\CSGO\SERVER. So there shouldn't be a space issue. 
But i tried the latest 2.1.3 version once again in C:\csgosl, just do be sure.
There is also enough diskspace left on my harddrive.

Just for info, i am running csgosl on a dedicated server, with windows server 2012.

It seems like the problems started after I accidentally forced closed a running server, without doing it with the console or csgosl (by just hitting the "x"). After that csgosl crashed instant and fired the a fatal error (looked like that, but it had nothing to do with workshop maps https://i.gyazo.com/5421db4142ced86f08a0d3eaf402e0cb.png ). Then I deleted all my csgosl files, and the server and tried it in a different folder.
There csgosl started, but now with the Applicationerror mentioned in this thread here.

**Comment by lenosisnickerboa** [comment] 2017-12-23 11:28
Sorry for the late reply, haven't had time for csgosl for a while...

I have never tested csgosl on "windows server 2012" so I'm not sure what to expect. Have you successfully run csgosl at any time on this installation of "windows server 2012"?

Have you successfully run the csgoserver (without csgosl) on ""windows server 2012""? Is it supported by Valve?

**Comment by realsliff** [comment] 2017-12-28 04:03
Yes sure, csgosl worked fine once.. and I am running a csgo server with srcds.exe / +.bat at the moment with no problems.

**Comment by lenosisnickerboa** [comment] 2017-12-28 14:35
OK, the error message you list above shows that it is the server status control script which somehow fails. This script is extremely simple and is used by csgosl to see if you have a server running. You could try running this script directly to see what happens. To do that simply navigate (using File Explorer) to your csgosl installation directory and enter the bin folder where the script server-status.bat is located. Right mouse button somewhere not on a file and select "Start command promt here" . In the command prompt window enter 'server-status.bat' and hit ENTER.

This is what it looks like for me (with no server running):
`D:\_NB\csgo test with spaces\csgosl\csgosl\bin>server-status.bat`
`not_running`

Try this and get back to me with the result.

What you also could try is executing the following commands to see what happens on your Windows Server 2012 installation:

`wmic process where "name='srcds.exe'" get ExecutablePath`

If you have no instance of the csgo server running it should give the following answer:

`No Instance(s) Available.`

Also try entering this command:

`find`

and report the result to me.

**Comment by lenosisnickerboa** [comment] 2018-01-11 17:01
Closing, no answer.

**Comment by lenosisnickerboa** [comment] 2018-01-11 19:05
This just happened to me so I've been able to reproduce the problem and will provide a fix. The problem is the wmic command for some reason is no longer available in the windows PATH variable.  The command is still present at C:\Windows\System32\wbem\wmic. An update is coming...

**Comment by lenosisnickerboa** [comment] 2018-01-11 19:20
Some more info on this, it does not require a csgosl fix since it is caused by a broken windows path. Simply reset the path to the default value and csgosl works again.

Default value:
%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem

[How to set it](https://www.computerhope.com/issues/ch000549.htm)

**BUT use the default value above instead of the one suggested in the article.**

**Comment by lenosisnickerboa** [comment] 2018-01-11 19:22
Not sure why this happens, could be caused by installing some program which modifies the path. In my case I suspect the "Python for windows" installer which modified the path. Not sure though.
Closing since this issue is now sorted.

**Closed by lenosisnickerboa** 2018-01-11 19:22 UTC

**Comment by ViolatorX** [comment] 2022-09-19 21:31
Might be that the same applies to some MS Server versions.

Starting with [Windows 11 build 22572, WMIC is only available as an optional feature that can be uninstalled or reinstalled. This process is very simple and only requires you to make some adjustments in the settings menu of your Windows 11 device. Here is how to add it.

Open Settings by pressing the Windows + I keys together.
Then, chooses apps Then, click Optional features.
Click the Feature display button.
Search for Wmic and check the box next to it and press Next.
Click the Install button.
