### ISSUE TITLE
"Fatal error" - csgosl.vbs is not starting anymore 

### ISSUE THREAD

**Issue by Rasko1337** [lenosisnickerboa/csgosl#69] opened 2017-03-05 03:19 UTC
I installed a server a couple of hours ago with your programm to host a LAN only server for an upcoming CSGO LAN with my friends. everything worked perfectly, but now i cant open the programm anymore. 
The following fatal error pops up when I'm trying to start csgosl.vbs: http://imgur.com/a/37Q26

All i did so far was adding some workshop maps / mapgroup to the server and also 2 plugins (Pause & Teamname Plugin) and i also changed some cfg's ( server.cfg ) and added some for the upcoming LAN Fun.
I also tried to change some of the workshop maps ingame from the collection i added and it worked too ( via "rcon changelevel workshop......" if i remember correctly
I
guess this error has something to do with the workshop map files / folders as the error message says? 
I already deleted all the downloaded Workshop Maps but it didnt help :/ same error over and over..

2nd "small" problem I had a couple of times was that I couldnt find the csgo server on "LAN" list at the community server browser and i couldnt connect to the IP via concole either :< what could that be? i didnt change any settings tho but somehow the server was not listed anymore and i made sure about sv_lan 1 in the steamcmd start commands too..
 
I really appreciate any help to fix this annoying error
Thanks in advance :)

**Comment by CJNiiva** [comment] 2017-03-05 10:58
Try deleting the workshop folder inside of csgo/maps worked for me, the problem is shutting down the server before the server has downloaded the workshop map

Sendt fra min iPhone

Den 5. mar. 2017 kl. 04.19 skrev Rasko1337 <notifications@github.com<mailto:notifications@github.com>>:


I installed a server a couple of hours ago with your programm to host a LAN only server for an upcoming CSGO LAN with my friends. everything worked perfectly, but now i cant open the programm anymore.
The following fatal error pops up when I'm trying to start csgosl.vbs: http://imgur.com/a/37Q26

All i did so far was adding some workshop maps / mapgroup to the server and also 2 plugins (Pause & Teamname Plugin) and i also changed some cfg's ( server.cfg ) and added some for the upcoming LAN Fun.
I also tried to change to some of the workshop maps of the collection i added and it worked too ( via "rcon changelevel workshop......" if i remember correctly
I
guess this has something to do with the workshop map files / folders as the error says?! I deleted all the downloaded Workshop Maps but it didnt help :/ same error over and over..

2nd "small" problem I had a couple of times was that I couldnt find the csgo server on "LAN" list at the community server browser and i couldnt connect to the IP via concole either :< what could that be? i didnt change any settings tho but somehow the server was not listed anymore and i made sure about sv_lan 1 in the steamcmd start commands too..

I really appreciate any help to fix this annoying error
Thanks in advance :)

**Comment by lenosisnickerboa** [comment] 2017-03-05 11:38
Yep, that's good advice, thanks CJNiiva. csgosl checks if the workshop folder is present but can't properly handle if it doesn't contain any maps. I will have a look at fixing this so that the workshop folder is ignored if it doesn't contain any maps.

**Comment by lenosisnickerboa** [comment] 2017-03-05 11:49
Just reproduced the error and a fix is coming any minute now :) Thanks for excellent error reporting, makes it so much easier...

**Comment by lenosisnickerboa** [comment] 2017-03-05 11:56
Release 1.3.1 delivered, closing.

**Closed by lenosisnickerboa** 2017-03-05 11:56 UTC

**Comment by exxis** [comment] 2017-03-08 00:16
i´am running the current version but still get the same error like Rasko1337 

https://i.gyazo.com/3622dcaed002141d7bd43521833aa5dd.png
