### ISSUE TITLE
Start Server don't work - some path problems?

### ISSUE THREAD

**Issue by Manni79** [lenosisnickerboa/csgosl#82] opened 2017-04-15 15:01 UTC
Hello, I have a new PC with Windows 10 now.  I wanted to check out new csgosl now, but run into Problems. It seems, that commands off cslgosl are not correctly executed  on my computer.

For Example click on "start server"

Console tab in GUI Shows me:
bin/server-start.bat "D:/Program Files (x86)/csgosl/server/srcds.exe"  -game csgo -console -usercon -condebug  +game_type 0 +game_mode 1  +mapgroup LAN_Group  +map aim_redline  +sv_setsteamaccount xxx -authkey xxxx  -maxplayers_override 12  -tickrate 128  +sv_password yyy    +hostname "yyyy" -port 27015 +sv_lan 0  +ip 0.0.0.0 +tv_enable 1

... but nothing happens. No Server start. no CMD Pop ups with Server start commands.

- Windows 10
- installed in D:\Program Files (x86)\csgosl

When i execute on command line the following

CMD: D:\Program Files (x86)\csgosl>
bin/server-start.bat "D:/Program Files (x86)/csgosl/server/srcds.exe"  -game csgo -console -usercon -condebug  +game_type 0 +game_mode 1  +mapgroup LAN_Group  +map aim_redline  +sv_setsteamaccount xxx -authkey xxxx  -maxplayers_override 12  -tickrate 128  +sv_password yyy    +hostname "yyyyy" -port 27015 +sv_lan 0  +ip 0.0.0.0 +tv_enable 1

then I get error message 
"'bin' is not recognized as an internal or external command,
operable program or batch file."

So it seems my Windows 10 is not understanding your command (because of the starting "bin" Folder path). But why? I think most of your user uses Windows 10 and then many People should have Problems. So it's curios.

when I do on command line
cd bin
then I am in CMD D:\Program Files (x86)\csgosl\bin>

and then execute your comamnd without bin/, then all works fine:

server-start.bat "D:/Program Files (x86)/csgosl/server/srcds.exe"  -game csgo -console -usercon -condebug  +game_type 0 +game_mode 1  +mapgroup LAN_Group  +map aim_redline  +sv_setsteamaccount xxx -authkey xxxx  -maxplayers_override 12  -tickrate 128  +sv_password yyy    +hostname "yyyy" -port 27015 +sv_lan 0  +ip 0.0.0.0 +tv_enable 1

and Server starts fine with that.

Any Idea ehy my PC /win10 have probelms with your command incl. path?

**Comment by lenosisnickerboa** [comment] 2017-04-16 05:19
Just a guess but you have spaces in the path to your csgosl folder. Some
people have problems with that. So try moving your csgosl folder to e.g.
c:\csgosl and try from there.

Den 15 apr. 2017 5:02 em skrev "Manni79" <notifications@github.com>:

**Comment by Meiogordo** [comment] 2017-04-16 15:03
I am having the same problem. I had the file in a directory that caused the path to have spaces but I changed the path so that it does not have spaces anymore. It seems that csgosl itself doesn't recognize the command... Navigating to bin using cmd and copy pasting the command from csgosl works for me I guess...

**Comment by CJNiiva** [comment] 2017-04-16 16:05
Any fix for this maybe?😂 love the app (you probably know that)

Sendt fra min iPhone

Den 16. apr. 2017 kl. 17.04 skrev Miguel Duarte <notifications@github.com<mailto:notifications@github.com>>:


I am having the same problem. I had the file in a directory that caused the path to have spaces but I changed the path so that it does not have spaces anymore. It seems that csgosl itself doesn't recognize the command... Navigating to bin using cmd and copy pasting the command from csgosl works for me I guess...

**Comment by lenosisnickerboa** [comment] 2017-04-17 12:51
Do you mean that csgosl fails to start the csgo server even when you move it to a path without spaces? 

If yes, can you all send me the complete paths where csgosl is installed so I can try to reproduce the problem.

If no, move csgosl to a path without spaces. I currently don't have time to fix this (and I don't see this problem when I try it on my windows 7 and windows 10 installations).

**Comment by Manni79** [comment] 2017-04-17 20:38
It's not a Problem of pathes with spaces, the Problem is the "bin/..." in the path, as  the error message described above.

I tried a bit and have a solution, very simple.

bin/server-start.bat ... (with  slash /)
... is not working. Error message:
'bin' is not recognized as an internal or external command,
operable program or batch file.

use **backslash** and it is working fine:

bin\server-start.bat ... (with **backslash** **\**) is working fine.

**Comment by lenosisnickerboa** [comment] 2017-04-17 21:35
Ok, I see. I'll go through all paths in the program and make sure to adapt them to the correct OS syntax. Thanks for finding the bug and a solution. 
Not sure though why this works for me? I have two windows servers, one with spaces and one without and also a linux server. They all worked fine with the 1.8.1 release. 
Hopefully I will fix this tomorrow evening, stay tuned...

**Comment by CJNiiva** [comment] 2017-04-18 11:25
Its still because of the spaces, as it tries to launch c://whatever (space) bin/something and then you get the cannot recognise bin/something because it tries to execute “bin/something” as a command, I don’t know, but it might help to add the “” to the command, for example “c://whatever (space) bin/something” :)

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by lenosisnickerboa** [comment] 2017-04-19 21:12
Sounds like you're having different problems with paths. I've reworked how server start/stop/update is performed in both windows and linux and it seems to be really stable, with or without spaces in paths. I will do some more testing and hopefully I will release 1.8.2 tomorrow fixing all the problems you've described above.

**Comment by lenosisnickerboa** [comment] 2017-04-19 22:33
Tested some more and I think it works. Here's 1.8.2 with fixes for various path problems. Enjoy! (And please reopen this issue if you still have problems :) )

**Closed by lenosisnickerboa** 2017-04-19 22:33 UTC
