### ISSUE TITLE
HLDS no longer launches after this morning's update

### ISSUE THREAD

**Issue by jasonboche** [lenosisnickerboa/csgosl#335] opened 2022-06-24 16:41 UTC
I noticed there was an update this morning. I updated the server. That went fine. Now when I click on Start Server, HLDS attempts to launch but crashes immediately. I also tried launching using the command line generated by csgosl. I'm not sure if this is a csgosl issue or not.

Thank you,
Jason Boche

**Comment by enerdk** [comment] 2022-06-24 19:31
I have the same problem.
I tried rename the server folder and re-download the csgo files but that change anything.

BR
EnerDK

**Comment by jasonboche** [comment] 2022-06-24 19:48
I restored my server from last night's storage snapshot. It worked (although it needed an HLDS update again). I applied the HLDS update. Once again it crashes immediately after launch. Hopefully this helps. I'm still not convinced it's a csgosl issue (unless one of the supplied parameters csgosl is providing is deprecated and causing the crash) but I thought I'd at least document the issue here for posterity.

**Comment by CSJoe2** [comment] 2022-06-24 22:02
I am having the same issue.

**Comment by lenosisnickerboa** [comment] 2022-06-25 10:13
Just updated and got the same issue (on windows, don't know about linux yet).
However, it seems related to sourcemod, see this similar problem from before: [problem](https://forums.alliedmods.net/showthread.php?t=263498)
When I disable sourcemod the server starts without crashing.
I will investigate if the latest sourcemod solves the problem and deliver a fix if so. Stay tuned.

**Comment by lenosisnickerboa** [comment] 2022-06-25 10:41
Just released [2.13](https://github.com/lenosisnickerboa/csgosl/releases/tag/v2.13) which fixes the reported issue. Thanks for reporting!

Also confirmed the same issue on linux and upgrading sourcemod solves the issue there as well.

Please close this issue when you have confirmed this solves your problems.

**Comment by jasonboche** [comment] 2022-06-25 15:05
I upgraded to 2.13 and the issue still exists on my Windows server. The server still crashes as soon as it's launched. I don't have a Linux server.

**Comment by CSJoe2** [comment] 2022-06-25 15:14
I did as well and am still having the issue. I have tried creating a new game server token an that has not helped either.  I am getting the same exact response as the user jasonboche in his video.

**Comment by enerdk** [comment] 2022-06-25 15:47
I also still have the problem.
One thing I noticed is if I try to start the server from command prompt with the line from cmd-start.bat.
It still crashes so I think it's a valve problem.

Seems also other have the problem:
https://steamcommunity.com/discussions/forum/13/3421061982936806411/

BR
EnerDK

**Comment by enerdk** [comment] 2022-06-25 16:05
https://forums.alliedmods.net/showthread.php?t=338289&page=5

Works for me..

**Comment by lenosisnickerboa** [comment] 2022-06-25 17:22
Thanks all for reporting back. This is weird, after having updated sourcemod it worked for me directly, both on linux and windows. Both linux and windows failed with the old 2.12 version. So I assumed this was a proper fix.
This is not a csgosl issue as mentioned above. It seems to be some incompatibility between csgo server and sourcemod, don't know who (Valve or sourcemod devs) will fix this though.

**Comment by CSJoe2** [comment] 2022-06-25 17:49
Updated the inputsystem.dll file that enerdk linked here https://forums.alliedmods.net/showthread.php?t=338289&page=5 fixed the issue for me.  Copying the file from my local game CSGO directory alone did not fix it for me, I downloaded the version shared on google drive and that fixed it for me.

**Comment by jasonboche** [comment] 2022-06-25 23:29
I followed CSJoe2's lead and replaced the inputsystem.dll file and that worked.

Thank you,
Jas

**Comment by CSJoe2** [comment] 2022-07-11 18:35
@lenosisnickerboa I think we are all good.  At least it has been working on my end the last couple of weeks.  Thank you for all of your work!  I really appreciate it.

**Comment by jasonboche** [comment] 2022-07-11 23:32
> Just released [2.14](https://github.com/lenosisnickerboa/csgosl/releases/tag/v2.14) I have no idea if this in any way solves any of the problems reported in this thread but it steps both sourcemod and metamod versions to the latest and csgo server also received some updates so perhaps the problem is resolved?
> 
> Since I never experienced the problem, and still doesn't, I can't really say if this thread should be closed. Please report back if the problems still exist or I will close this thread in a couple of days.

The 2.14 release does not alone fix the original issue. To test this as a solution, I rolled back inputsystem.dll back to the original version you were shipping as of 2.13. The date/time stamp is 6/24/2022 10:14 AM.

Then I used the csgosl automatic upgrade process to upgrade to csgosl 2.14.

After the upgrade was complete, I tried launching a server and it is back to crashing immediately. I then went into the C:\csgosl-windows\csgosl\server\bin folder and checked the inputsystem.dll. It still has the same date/time stamp of 6/24/2022 10:14 AM which tells me the DLL was not changed as part of the 2.14 changes.

Lastly, I replaced inputsystem.dll with the patched version talked about earlier in the thread. It has a date/time stamp of 7/6/2022 9:23 AM (probably the date downloaded it). I am now back to being able to launch a server.

Thank you,
Jas

**Comment by lenosisnickerboa** [comment] 2022-07-13 09:48
Thanks for your comments. Just a note, it's not csgosl which distributes the inputsystem.dll file (unpack the csgosl-windows.zip archive and have a look). That dll is distributed by Valve when performing a server upgrade. I have no idea why this file isn't updated when you perform the upgrade though? Could be something related to permissions? Owner? 

Anyway, closing this issue. Please reopen if some problem occurs again.

**Closed by lenosisnickerboa** 2022-07-13 09:48 UTC

**Comment by jasonboche** [comment] 2022-07-13 14:48
> Thanks for your comments. Just a note, it's not csgosl which distributes the inputsystem.dll file (unpack the csgosl-windows.zip archive and have a look). That dll is distributed by Valve when performing a server upgrade. I have no idea why this file isn't updated when you perform the upgrade though? Could be something related to permissions? Owner?
> 
> Anyway, closing this issue. Please reopen if some problem occurs again.

Oh sorry about that - I should have checked. That was a massive assumption on my part.

Jas
