### ISSUE TITLE
game server token and apiauth

### ISSUE THREAD

**Issue by R0m41n3** [lenosisnickerboa/csgosl#107] opened 2017-11-12 00:07 UTC
neither are working when i boot the server. they seem like they don't get entered into the console.

**Comment by lenosisnickerboa** [comment] 2017-11-14 19:42
Still a problem?
If yes, see this: [Report a bug](https://github.com/lenosisnickerboa/csgosl/wiki/Report-a-bug)
This is really basic functionality which makes me wonder... 
Have you just used csgosl to setup the server or have you edited configuration files yourself? 
Does it help if you set everything to default and then reenter the server token and api auth key?
Does the server start even though the server token and api auth key is not working?

**Comment by lenosisnickerboa** [comment] 2017-11-14 19:52
One more thing, haven't played for a while and noticed my game server login token had expired. Have you checked yours here: [http://steamcommunity.com/dev/managegameservers](http://steamcommunity.com/dev/managegameservers)

**Comment by mikevmark** [comment] 2017-12-10 12:40
I have the same problem and followed your suggestions above as well. I also did a complete re-installation of csgosl including re-downloading the server(game?) itself. I generated new server token and auth keys as well. In the server window, it says "No Steam account token was specified. Logging into anonymous game server account." This is on windows with all latest versions. 
I installed csgosl by itself and used it to install the server, i didnt add it to an existing install. Any ideas or ways i can help?

**Comment by lenosisnickerboa** [comment] 2017-12-11 08:43
Thanks for getting back with the "Lan only" checkmark findings. Could be the clue I need to find what is causing all this. I will have a look when I get back from work today to see what could cause this behaviour.

**Comment by lenosisnickerboa** [comment] 2017-12-11 08:44
Sorry, closed by mistake :)

**Comment by lenosisnickerboa** [comment] 2017-12-11 21:03
I reinstalled (on windows) from scratch using latest version 2.1.3 without problems. Couldn't reproduce the lanonly issues you describe, it stayed unchecked once I unchecked it. The only things I changed after having installed the server were:
Server page: lanonly disabled
Steam page: Entered steamusername, steamid, gameserverlogintoken, apiauthkey
Started server with no issues.
Did you change something else? Something under Sourcemod tab?

**Comment by Creston1** [comment] 2017-12-16 21:29
I'm getting the same issue, and it's incredibly annoying.

**Comment by lenosisnickerboa** [comment] 2017-12-23 11:24
Sorry, "same issue" is a bit vague, can you specify more exactly what you're experiencing? Also, @mikevmark mentioned the problem somehow disappeared, this is not happening for you I guess? Have you tried complete reinstall with only the changes I propose above?

**Comment by lenosisnickerboa** [comment] 2018-01-11 17:02
Closing, no answer, reopen if this is still an issue.

**Closed by lenosisnickerboa** 2018-01-11 17:02 UTC
