### ISSUE TITLE
The standard config is wrong (everymode)

### ISSUE THREAD

**Issue by CJNiiva** [lenosisnickerboa/csgosl#36] opened 2016-06-13 01:18 UTC
you dont get a starting pistol when you start a clean install, even on competitive, I ran in to this issue when I was going to have a Gather, but fixed it with a plugin called Pugsetup, really annoying and I cant find the command to get it back either:/

**Comment by lenosisnickerboa** [comment] 2016-06-16 19:44
Haven't had any issues like these myself and no one else has reported it, strange... Could you elaborate some more on what happens? You say "clean install", does that mean the problem somehow goes away after a while? Is this still a problem for you?

**Comment by CJNiiva** [comment] 2016-06-16 19:59
the problem is still there, I have bought a server, but on my local servers are still there, I can make a video about it tomorow:)

**Comment by spiral6** [comment] 2016-06-21 04:44
I can concur this issue exists. Went back to my old manual server and copied the configs back.

**Comment by lenosisnickerboa** [comment] 2016-06-21 21:03
A video would be nice. I need some more info to be able to understand what the problem is. I have reinstalled csgosl a number of times on both windows and linux and I don't see this problem.

By "you dont get a starting pistol" do you really mean you clean install, start server, start a game client and then you can't select a any gun?

**Comment by spiral6** [comment] 2016-06-26 23:08
@lenosisnickerboa That is incorrect. I installed this for the first time, updated server, set configs, and started server. Then I started the client and joined in. All the kill bonuses are wrong (no money awarded for each kill), no starting primary or secondary, and changing any configs does not have any changes apply, despite them being saved.

**Comment by spiral6** [comment] 2016-06-26 23:19
Overriding the configs with my own server configs has no effect upon the server. All the default configs are still completely wrong.

**Comment by lenosisnickerboa** [comment] 2016-07-05 10:28
There must be something fundamentally wrong with your installation and its hard to help you out without more info. Starting primary and secondary weapons, kill bonuses, ... are not even handled by csgosl so you should get whatever you get when manually installing. 

I'm also puzzled about the fact you're saying settings are not changed/saved, still you say things don't work? If csgosl didn't save/change setting then you should get exactly what a manual install gives you, right? It seems a bit contradictory to me.

If you perform a clean install, ensure you have free diskspace where you install and proper folder permissions I can't see how you can fail. 

Are you running windows or linux?

**Comment by spiral6** [comment] 2016-07-05 14:54
Running Windows 10 x64. I'll give it another shot. I'm going to delete csgosl and uninstall it completely. Then I am going to redownload the program, run the executable script, and install the server again. Then I'm going to launch the server in competitive, and join in. If there still isn't a starting pistol, then something's wrong with the configs.

**Comment by lenosisnickerboa** [comment] 2016-07-05 17:14
Yes, please try that and get back to me with the result. Just start the
server using all default values, don't change anything. If you run into the
problem again it would be great if you could record some video or take a
screenshot showing the problem.

Good luck!
Den 5 juli 2016 4:55 em skrev "Shamee Mahmud" <notifications@github.com>:

**Comment by xTRiiME** [comment] 2016-07-27 10:01
Have the same Problem. Fresh install nothing special changed. No pistols at spawn. You spawn only with a knife but you can buy anything... Help?

**Comment by lenosisnickerboa** [comment] 2016-07-27 11:07
Thanks for investigating, I'll have a look. It sure looks funny though since none of the options above are directly controlled by csgosl... Stay tuned.

**Comment by xTRiiME** [comment] 2016-07-27 11:17
There are 2 files:
gamemode_competitive.cfg
gamemode_competitive_server.cfg
this server cfg doesn´t exist in the original build.
Maybe this is converted from csgosl?

**Comment by lenosisnickerboa** [comment] 2016-07-27 12:44
The <gamemode>_server.cfg should contain your changes per game mode, one
should never change anything in the <gamemode>.cfg file since it will be
overwritten (by Valve/steamcmd) when updating the game. csgosl will
create <gamemode>_server.cfg files for all game modes but shouldn't really
change anything. But while writing this I suspect the code which creates
these default <gamemode>_server.cfg files may be a bit sloppy. Will check
as soon as I have a few minutes to spare.

**Comment by xTRiiME** [comment] 2016-07-27 14:20
Maybe found it dunno.
mp_ct_default_melee ""
mp_ct_default_primary ""
mp_ct_default_secondary ""
this is found in the csgosl config folder in gamemode_all.txt
csgosl is picking the values from there so if they are not set they will be 0

**Comment by CJNiiva** [comment] 2016-08-27 10:21
Oh shit, I totally forgot that I reported this bug, I'm glad you guys figured it out:D and sry for not replying

**Comment by spiral6** [comment] 2016-08-27 21:21
I don't think it's figured out yet @CJNiiva but it's getting closer.

**Comment by lenosisnickerboa** [comment] 2016-08-28 19:28
I've had no time for csgosl for a while but when I do I will have a look at
this again. Thanks for all input!

**Comment by lenosisnickerboa** [comment] 2016-10-15 11:44
A new version (1.2) is coming sometime today... The problems above are now fixed. See change notes for more details.

**Closed by lenosisnickerboa** 2016-10-15 11:44 UTC
Labels: bug, question

**Comment by spiral6** [comment] 2016-10-16 21:51
Thanks a lot.
