### ISSUE TITLE
Map groups crash

### ISSUE THREAD

**Issue by Tiimothe** [lenosisnickerboa/csgosl#299] opened 2021-01-16 16:53 UTC
When I want to create a new map group I click on "+" and csgosl freeze and I have to close it manually.
And when I click on the card list on the right I have the message "error: key "" not know in dictionary

**Comment by lenosisnickerboa** [comment] 2021-01-17 18:02
Please read [this](https://github.com/lenosisnickerboa/csgosl/wiki/Report-a-bug) and provide some more info to give me a chance to solve your problem. I haven't heard about this issue earlier and I use the map groups quite frequently myself.

**Comment by martinkuna** [comment] 2021-01-24 09:43
> When I want to create a new map group I click on "+" and csgosl freeze and I have to close it manually.
> And when I click on the card list on the right I have the message "error: key "" not know in dictionary

I'm getting the same issue, never used csgosl before, followed directions and even without making any configuration changes, same experience.

**Comment by Tiimothe** [comment] 2021-01-30 13:02
Sorry for the time I got to answer.
csgosl version: 2.9.4
platform: Windows 10 (French)
![2021-01-30 13_49_35-Window](https://user-images.githubusercontent.com/77543882/106356726-0d59b780-6302-11eb-8e49-5a83d1f1b122.png)
I click on "+" and csgosl freeze
I have to use the task manager to close it.
-/copy/rename don't freeze but do nothing 
and when I left-click on the map list I have this
![2021-01-30 13_48_25-Window](https://user-images.githubusercontent.com/77543882/106356789-7c371080-6302-11eb-828a-29ae14822fe8.png)
details: 
key "" not known in dictionary
key "" not known in dictionary
    while executing
"dict get $mapGroupsMapper $mapGroup"
    (procedure "GetMapsFromSelectedMapGroup" line 3)
    invoked from within
"GetMapsFromSelectedMapGroup $selectedMapGroup"
    (procedure "ClickedMapsListBox" line 4)
    invoked from within
"ClickedMapsListBox .config.n.mapGroups.scrollableitems.canvas.container.content.func11.groups.lbframe.lb .config.n.mapGroups.scrollableitems.canvas.co..."
    (command bound to event)

I don't use other server or mods.
It appends every time and never work since installation. No rcon. No console output.

**Comment by lenosisnickerboa** [comment] 2021-01-31 15:48
Thanks! A lot better, will have a look as soon as I get the time.

**Comment by Tiimothe** [comment] 2021-01-31 17:04
I deleted the files, but it still doesn't work.
Here are the contents of the files after a crash :
mapGroups.cfg:
// csgosl 2.9.4 config 1 at Sun Jan 31 17:53:51 CET 2021 (DO NOT TOUCH THIS HEADER LINE!!!)
mapGroups ""

mapGroupsMapper.cfg is empty

**Comment by lenosisnickerboa** [comment] 2021-01-31 18:30
Weird, tried everything now I think, both windows and linux and it just works. Removed one or both cfg files, emptied them, but I can always press "+" to create a new map group.

Just to be absolutely sure:

1. You start csgosl
2. Select "Map groups" tab
3. Click '+'-button -> gui freezes

?

**Comment by lenosisnickerboa** [comment] 2021-01-31 18:59
@Tiimothe , just released https://github.com/lenosisnickerboa/csgosl/releases/tag/v2.9.5 with some more guard code when running with empty map groups. If the problem isn't what I'm suggesting in the previous post perhaps this guard code will help. Please report back when you have tried all suggestions.

**Comment by jankcat** [comment] 2021-02-18 03:16
I am on 2.9.5, have tried all suggestions in this issue, and I have the same issue.

**Comment by lenosisnickerboa** [comment] 2021-02-20 10:16
@jankcat, @Tiimothe and @martinkuna could you all please retry this on 2.9.5 and send me the error dialog with the details button clicked (the dialog box below with all details shown):

![image](https://user-images.githubusercontent.com/16888566/108592149-bb3e0c00-736c-11eb-83ad-a290b556ae47.png)

It can hopefully show the troublesome part(s) of the code (could be different parts). I fixed some parts without really experiencing any problems myself but if I can see the parts causing problems for you I can try and add some guard code there as well.

**Comment by martinkuna** [comment] 2021-02-23 18:58
@lenosisnickerboa On 2.9.5, clicking on either arrow produces the following:
![image](https://user-images.githubusercontent.com/6981410/108893123-f3905500-75cd-11eb-8bb7-748261d600c2.png)
```
bad listbox index "": must be active, anchor, end, @x,y, or a number
bad listbox index "": must be active, anchor, end, @x,y, or a number
    while executing
"$lbMapGroups itemconfigure $selectedMapGroupIx -selectbackground lightgrey"
    (procedure "UpdateMapGroup" line 16)
    invoked from within
"UpdateMapGroup .config.n.mapGroups.scrollableitems.canvas.container.content.func11.groups.lbframe.lb .config.n.mapGroups.scrollableitems.canvas.contai..."
    invoked from within
".config.n.mapGroups.scrollableitems.canvas.container.content.func11.synch.buttons.update invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 24)
    invoked from within
"tk::ButtonUp .config.n.mapGroups.scrollableitems.canvas.container.content.func11.synch.buttons.update"
    (command bound to event)
```
Clicking on the + button freezes the GUI without error; however, the window can still be moved around and does NOT show any indication of a freeze (like Not Responding...). I can hover over minimize, maximize and exit as if it was not frozen, but when I click on the windows bar X to exit, it does nothing.

**Comment by lenosisnickerboa** [comment] 2021-02-23 19:42
Thanks! The first problem is easily reproduced, clicking on <-- when no mapgroup exists. That I can easily fix.
The second though still doesn't happen to me. When pressing + I always get the "Add mapgroup" dialog (on the first monitor, running csgosl on the second monitor). Even after having tried clicking <-- and getting the error I still get the "Add mapgroup" dialog. Can you please explain exactly how you get the freezing GUI, from starting csgosl.

**Comment by martinkuna** [comment] 2021-02-24 20:37
@lenosisnickerboa It's also interesting to me that it shows _Number of map groups: 1_ in the GUI when the config file contains none.

I'll test later tonight and get back to you, thank you for the help.

**Comment by martinkuna** [comment] 2021-02-27 01:14
@lenosisnickerboa I am at a loss, tried it with one monitor and no other gui's/windows open, moved the window all around, nothing... Clicking "+" simply blocks the user from interacting with the GUI with no window off screen or hidden behind taskbar/etc that I can find. It's like it executes the GUI and blocks interacting with the parent GUI, without being a part of the OS's window manager lol.

**Comment by lenosisnickerboa** [comment] 2021-03-28 19:58
Sorry, haven't had time to read github issues for a while. I can't reproduce the error and the only way forward is if you can explain exactly how you get the freezing GUI, from starting csgosl. Exactly every step/click and I can try to reproduce it again. Or if you record a clip and post it here showing how you get the problem. Else I'm kinda stuck here.

**Comment by NahuelRaspanti** [comment] 2021-04-12 22:05
I have the same problem. After I open csgosl just go to "Map Groups" click on the "+" button and it freezes.. nothing else. The only thing I can think of is I had the steamcmd and cs go files in another folder already so i have to move them to the csgosl folder before using it, I don't know if that's of any help but I can't think of anything else. Apart from that the program works fine

**Comment by lenosisnickerboa** [comment] 2021-04-24 17:54
Just released 2.9.6. Please test and see if this fixes your problems. Please report back on your success, good or bad, so I know.

**Comment by NahuelRaspanti** [comment] 2021-04-24 23:37
> Just released 2.9.6. Please test and see if this fixes your problems. Please report back on your success, good or bad, so I know.

It's working for me after the update!! Thank you!

**Comment by lenosisnickerboa** [comment] 2021-04-25 08:50
Great to hear! Thanks for reporting back.

**Comment by lenosisnickerboa** [comment] 2021-04-25 12:26
Closing this issue, please reopen if you continue having problems,

**Closed by lenosisnickerboa** 2021-04-25 12:26 UTC
