### ISSUE TITLE
Adding a new tab with the most used commands would be great:D

### ISSUE THREAD

**Issue by CJNiiva** [lenosisnickerboa/csgosl#73] opened 2017-03-09 13:14 UTC
having a tab with the most used commands would be great:D like sv_enablebunnyhop and sv_autobunnyhop (I'm sure thats the command, but I always use the autothing in the console for these 2) also sv_airaccelerate etc, would be great:D

**Comment by CJNiiva** [comment] 2017-03-09 13:15
you could also have a session here on github where people could add commands to that tab so that the most used commands for everyone is there:D

**Comment by lenosisnickerboa** [comment] 2017-03-09 21:09
Not sure I completely understand what you want. Do you mean something like string entries where you can add any command and value or do you mean adding most used options like all other csgosl options, i.e. that I add buttons, checkboxes, number entries ... depending on the option you want to control?

The first alternative could be located on a separate tab with just a number of empty string entries. If you mean the second alternative that probably would mean adding more options to the already existing tabs, right? Since I have tried to gather options into related groups like Server, Steam, Sourcemod, ...

So the sv_enablebunnyhop and sv_autobunnyhop could be two checkboxes on the Run tab and sv_airaccelerate could be a number entry on the Run tab. 

So, please explain some more what you want and I'll certainly consider it.

Also, do you know a good source describing all commands? There's e.g. the one I used for the all command tabs [All commands](https://developer.valvesoftware.com/wiki/List_of_CS:GO_Cvars) but it doesn't seem to be updated, e.g. doesn't contain the one's you're suggesting,

**Comment by Manni79** [comment] 2017-03-11 12:10
I think the Issue Author just wants more cvars  in the existing tabs.

But I think the idea of being able to customize the tabs is much better. I also miss cvars on the "Run" tab and also on the detailed tabs wit cvars to each gaming mode. I want to save in csgosl more and different cvars for different game modes.

I think a solution with "*_custom_cvar"-cfg-files would be nice for each tab. 
The files should exist in your csgosl folder for every tab like "run", "all modes" and for each gaming mode. Then everybody can go into these files and add own cvars. When someone edit a "*_custom_cvar"-cfg files and add cvars, you should on csgosl start read all "*_custom_cvar" cfg files and show in every tab the cvars a user has added to these files. 
Plus, the user should be able to see and edit the custom cvars in csgosl gui interface, ones new custom cvars are added to these files by the user.

In the tabs "run", "all modes" and every gaming mod, you can add (on the bottom) a big line as separator, with a big title "Custom Cvars". 
And as subtitle: "All following cvars are customized CFGs" or better for every sheet you can write a subtitle, which point directly to the custom file wich is used.
Subtitle example for Custom Cvars in "all modes tab" should be: 
"All following cvars are out of custom file: /cfg/gamemode_all_Custom_cvars.cfg"

You only have to show the user the separator and the subtitle, if he had entered cvars in the corresponding custom_cvar file. If a user has no customization, you  don't need  to show separator and subtitle on the tabs.

Show the Info only, where the user has added custom cvars in the new custom_cvar cfg files.

Of course you can add more functionality to this. You can have a "New" button in  the "custom cvar" section of each tab, to add new cvars. If you use the "new" button and add the cvar, the cvar should be written to the corresponding custom-cvar-cfg. Also a "delete" button make sense. But I think you don't need the buttons, every user who want to make customizations like this, could be as experienced, to do it with manual file editing. For me, it would be very nice and good enough.

On every tab, which supports adding cvar customization, you should add the customize section separator on the bottom of the tab content site. Followed by the subtitle, followed by the custom cvars out of the corresponding custom-cvar-files.

I think that would be great, and it is also a solution for the Author of this issue. Because then, he can go to the files vor customized cvars for "all gamodes" or for the "run tabs" and then add his missed cvars " sv_enablebunnyhop and sv_autobunnyhop" there. And ones he add theses cvars in the custom-cvar-cfgs for "run" tab and "all gamemode" tab (and re-starting csgosl) he can administrate, see and change these cvars settings right out of csgosl.

I would really love to see such a feature in csgosl. I think many people have more cvars they  want to add  to the the tabs. Same for me. And then everybody can add cvars to tabs he want.

The cvars in the custom files should be executed last. If someone add cvars in a custom files, which already exist it in corresponding original file, the custom cvar setting should be the active one.

Best regards
Manni

**Comment by lenosisnickerboa** [comment] 2017-03-11 22:27
Thanks @CJNiiva  and @Manni79 for a lot of good input. Yes, some kind of user defined cvars would be nice and I've also considered it. Some thoughts on the subject...

First of all, adding a user defined option also means defining a type for that option. That type is used to select how to represent that option, e.g. by a toggle button (on/off), a dropdown listbox (e.g. select one of many gamemode types), an integer number (e.g. number of players) or simply a string (e.g. the server name). Most options also have a default value. Furthermore, some options are command line options, others go into server.cfg, and still others go into gamemode specific cfg files. csgosl is intended to hide all this from the non experienced end user to allow "anyone" to start a csgo server with some sane defaults and easy tweaking of the most common options. 

Having said all that, to allow user defined options, the user would have to be able to specify option name, type, default value, where the option is used (command line, which config file, ...). This could of course be done with a "New" button where the user has to specify all this.

Configuration files could of course also be a way to do it, but then we're pretty much back where I started with csgosl, wanting to avoid people having to find and edit config files.

Another aspect is getting csgosl to provide the "right" options, i.e. the ones most people are interested in. By adding user defined options each user can add their own options but csgosl will not be improved with these wanted options which would benefit all users.

Well well, of course csgosl could support all of the above. I'll have to think some more about this. Meanwhile I will add an issue for wanted options in csgosl.

And keep the ideas coming :)

**Comment by Manni79** [comment] 2017-03-12 11:54
For me, I would first assign only the "normal" cvars which a player can also enter in CS console when server is running. So all mp_*, sv_* and other settings, which could be on the "all modes" and on the dedicated tabs for each game mode.

And for me, the customized section in first shot with simple text, should not need special "types". Everything can be type string, for the option. In string, everybody can simply enter a "string" or also a number "2". It should simply work, also without using GUI.

When the user add  some cvars to the new files
"/cfg/gamemode_cacual_custom_cvars.cfg", or "/cfg/gamemode_all_custom_cvars.cfg", ...
like ...
sv_enablebunnyhop "1"
sv_autobunnyhop 2 ...
then csgosl should simply read it, order it, correct the format (e.g. double blanks, etc) and show it on the new "custom" section on the buttom of both tabs.

Of course you can make in the feature much more improvement:
- New button with supporting correct cvar type (also default value and explanation) on often used cvars
- delete button
- tool tips for the custom cvars, to explain the settting
- implement default values and  show default value on GUI-fiel-color and tooltip
- checking type when editing for the "often used2 cvars for which you have implemented already the correct type. (Rest simple string without type and without explanation, when not cvar implemented yet)
-- But all the improvements can work fine with the new files like "/cfg/gamemode_XY_custom_cvars.cfg". And I think you don't have to change it, even with adding later better usability and better user support for custom cvars. First the simple text files would be a great improvement.


> Another aspect is getting csgosl to provide the "right" options, i.e. the ones most people are 
> interested in. 

Yes, in the 2nd shot with more improvemts, you can add the new button. In the "New" Button you can simply implement als that to extend the usability. New Button  can support, showing often used cvars, explanation of them, default value shoeing, correct type, a check if the cvar can be used in the corresponding tab. You can also implement a "edit" button wich support al of it. But for  the data saving, I see very simple flat text files like normal cvar-cfgs, which everybody can also simply edit on text level and re-start csgoesl.

**Comment by lenosisnickerboa** [comment] 2017-03-12 19:18
So, I just released 1.5. Have a go and see what you think. It is somewhat described [here](Custom-cvars).

**Comment by Manni79** [comment] 2017-04-15 15:14
I tried now, but it's not working for me. I tried on Classic_Casual, clicked on new cvar

... entered:
- mp_autoteambalance
- 0
- fsdds

Nothing happens. I am not seeing  mp_autoteambalance in the list then.

Thanks and best regards
Manni

**Comment by Manni79** [comment] 2017-04-15 15:15
btw, would be nice when you could to a alphabetic sort on all Tabs. It's a bit disordered at the moment. :-)

**Comment by Manni79** [comment] 2017-04-16 00:17
Perhaps I have missed that a restart of csgosl is required? I started after hours again, and now i see my custom cvar.

**Comment by lenosisnickerboa** [comment] 2017-04-16 05:22
Yup, that's it.

Den 16 apr. 2017 2:18 fm skrev "Manni79" <notifications@github.com>:

**Comment by Manni79** [comment] 2017-04-16 20:46
It's not working for mp_autoteambalance and mp_limitteams.
Bit I can change it with rcon when I am on the Server. Anything Special with these?

**Comment by CJNiiva** [comment] 2017-04-16 20:47
If its on the list I'm guessing its a matter of what is executed first, my guess is the top to bottom

Sendt fra min iPhone

Den 16. apr. 2017 kl. 22.46 skrev Manni79 <notifications@github.com<mailto:notifications@github.com>>:


It's not working for mp_autoteambalance and mp_limitteams.
Bit I can change it with rcon when I am on the Server. Anything Special with these?

**Comment by Manni79** [comment] 2017-04-16 20:50
Perhaps I waswrong, and it is not working at all for me, i am not sure for now. I have to test a bit more. Or perhaps it is also influenced by my other Problem of starting on command line by myself. Problem of other thread.

**Comment by Manni79** [comment] 2017-04-20 20:38
It's not working and I took a look in CSGO Folder and I don't understand how it should work. For normal changes a user made in csgosl I think you write all settings in a *_settings file. On CSGO start, the game ready also the *_settings files and and activate your csgosl settings.

But how do you think the "custom" cvars were read by the game on start? I see, you write all custom cvars in a *custom file. But I don't think this will be read be the game on start. So how do you think the custom cvars were activated on game start?

Perhaps I miss something. :-(

**Comment by lenosisnickerboa** [comment] 2017-04-24 18:27
Sorry, missed this email. Can you explain what the problem is? I don't
understand. A concrete example of something you think doesn't work may help.

**Comment by lenosisnickerboa** [comment] 2017-05-29 20:23
Closing, no answer. Please reopen if still an issue.

**Closed by lenosisnickerboa** 2017-05-29 20:23 UTC
Labels: enhancement
