### ISSUE TITLE
Error on starting server

### ISSUE THREAD

**Issue by BBlutin** [lenosisnickerboa/csgosl#136] opened 2018-04-05 11:24 UTC
Hi, i try to run the server on Ubuntu.

When i hit the Start button od csgosl, the command prompt show this error:

ERROR: Invalid game type 'csgo' specified.

What can i do ?

PS: I already fill all the requested steam,etc infos in csgosl

**Comment by lenosisnickerboa** [comment] 2018-04-05 13:00
Tried a google search for your error message and it lead me [here](https://forums.alliedmods.net/showthread.php?t=230025). Have you tried changing to another (smaller) map?

**Comment by BBlutin** [comment] 2018-04-05 13:58
Im trying several things since yesterday but i cant find a solution ... 

I have searched aprox 4hours on google but i found nothing that resolve the error

**Comment by lenosisnickerboa** [comment] 2018-07-24 11:55
Closing, no reply.

**Comment by kusayuzayushko** [comment] 2018-09-02 16:04
Same error with default settings

`23:03:05: Creating command script /mnt/fcb3330e-5866-46d0-8770-e52897a149e4/csgosl/bin/cmd-start.sh containing command "/mnt/fcb3330e-5866-46d0-8770-e52897a149e4/csgosl/bin/server.sh" start "/mnt/fcb3330e-5866-46d0-8770-e52897a149e4/csgosl/server/srcds_run"  -game csgo    +game_type 0 +game_mode 0  +mapgroup "<allmaps>"  +map de_dust2     -maxplayers_override 16  -tickrate 128      +hostname \"Your server at desctop operated by csgosl\" -port 27015 +sv_lan 1  
ERROR: Invalid game type 'csgo' sepecified.
Sun Sep  2 23:03:05 +07 2018: Server Failed`

**Comment by lenosisnickerboa** [comment] 2018-09-03 20:13
Googled and found [this](https://forums.alliedmods.net/showthread.php?t=230025)
"Something" crashes and the error message is the one stated above. Seems to be caused by various crashes in csgo itself or any added mods. Don't know how to proceed with this one?
Did it happen after you added a new map? A new mod? Enabled a new mod?
Anything you can come up with which was changed from where it all worked til it stopped working would help.

**Comment by lenosisnickerboa** [comment] 2018-09-22 21:16
closing, no response.

**Closed by lenosisnickerboa** 2018-09-22 21:16 UTC
